### ISSUE TITLE
Github Webhooks returning 404 Not Found

### ISSUE THREAD

**Issue by jvcjunior** [zpnk/stage-ci#19]
Hey guys, how are you?

I've tried to follow these steps: https://stage.now.sh/
After I deploy to my now account I went to step 4 and forward. I did everything as the website says but when github creates the webhook, this is happening:

![error1](https://cloud.githubusercontent.com/assets/397790/26150996/54b47e82-3ad7-11e7-8afc-042221027ac5.png)

What I did wrong? OR anyone here already faced that?

**Comment by richmccartney** [comment]
I've also been getting the same issue when going through the setup. Would love some insight @zpnk :)

**Comment by zpnk** [comment]
@jvcjunior If you try to redeploy stage-ci does the same thing happen? One thing I notice about your screenshot is that the url is `https://reactconf-hrpvs...`.  This is *not* the right url for stage-ci, it should be something like `https://stage-ci-abc123..`. Could you try again and if it's still not working post the steps you took? Thanks!

**Comment by zpnk** [comment]
@richmccartney If you check your repo's webhook settings, do you have a url that starts with `https://stage-ci-[random]`? This is important as that means the webhook is pointing to the right server. Could you try redeploying and if it's still not working post the setup steps you took? Thanks!

**Comment by jvcjunior** [comment]
Hey @zpnk I'll try! Thanks for your answer!

**Comment by jvcjunior** [comment]
Hey @zpnk I've tried but it's returning this message:

`Deploy failed, please check the repo and try again.`

I'm using like this:
![now-cli](https://cloud.githubusercontent.com/assets/397790/26782543/7bb0ab1c-49ca-11e7-93ca-a5711a222ecb.PNG)

I'm using my token from now account. I've created a github_token as well and set some string as webhook_secret. 

Is there a way of check what's happening? Thanks in advance!

**Comment by zpnk** [comment]
@jvcjunior I think that was due to deploy.now not support Docker-based projects (which stage.now is). 

This has been fixed in zpnk/deploy.now#8, so if you re-deploying using [this url](https://deploy.now.sh/?repo=https://github.com/zpnk/stage-ci&env=GITHUB_TOKEN&env=GITHUB_WEBHOOK_SECRET&docker=true) or the button on https://stage.now.sh it should work. If not please let me know.

Closing for now, thanks for the report! :)

Related: #12, #22

**Comment by jvcjunior** [comment]
Thank you @zpnk I believe it's working now:

![deploynow1](https://cloud.githubusercontent.com/assets/397790/26827438/a31335e8-4a93-11e7-815c-8552c31e5796.PNG)

But when I click on the link, it's opening something like this:

![deploynow2](https://cloud.githubusercontent.com/assets/397790/26827448/b13c88e0-4a93-11e7-86dd-e0a95a279b74.PNG)

Do you have any idea why?

Actually our project are not docker based. This project was bootstrapped with Create React App.

**Comment by zpnk** [comment]
@jvcjunior Good news, seeing that json response means that stage-ci deployed successfully!

The next steps are to copy that `stage-ci-wfw...` url and set it up as a webhook on your GitHub repo. Check out the directions [here](https://stage.now.sh/), from step 4 onward. Let me know if you run into any issues. :)

RE: Docker - the issue was not with your project, but the [deploy.now](https://deploy.now.sh) service we use for the deploy button on [stage.now](https://stage.now.sh). Sorry for the confusion!

**Comment by jvcjunior** [comment]
@zpnk I did all steps after 3. But how can I access the deployed page?

**Comment by zpnk** [comment]
@jvcjunior This is the way stage-ci works:

- user deploys stage-ci to now, gets a url like `stage-ci-abc123.now.sh`.
- users configures that url as a webhook on a GitHub repo.
- when a pull request is opened (or pushed to) on that repo, the code of that PR is deployed to now.
- the url of the PR deployment will be shown on the pull request.

Does that make sense?

**Comment by jvcjunior** [comment]
@zpnk I see!! Thanks for your answer! It's working!!!! I appreciate your help..

**Comment by zpnk** [comment]
@jvcjunior Glad it's working for you, thanks for using stage!

**Comment by jvcjunior** [comment]
Thank you man!! And congratulations.. It's a great project! ;)
