### ISSUE TITLE
Deploy failed twice

### ISSUE THREAD

**Issue by kentcdodds** [zpnk/stage-ci#22]
Unfortunately there's not any log or anything :-(

<img width="396" alt="screen shot 2017-05-30 at 9 23 51 am" src="https://cloud.githubusercontent.com/assets/1500684/26591073/b9046e78-4519-11e7-9cb0-6cd77bb4632a.png">

**Comment by kentcdodds** [comment]
I got this deploying ok manually. So there's something weird about the deploy button I guess.

**Comment by zpnk** [comment]
Hey @kentcdodds 👋  - sorry you ran into this issue. The deploy button currently does not support Docker based deploys as mentioned in #12. Hopefully I will have some time soon to fix that in the deploy.now project.

The manual deploy works as the now-cli correctly detects the Docker project.

**Comment by kentcdodds** [comment]
Perhaps we should note this in the README 🤔

**Comment by jimthedev** [comment]
To be honest, the deploy button is nice but ultimately the lack of docker support might just end up causing more confusion. What do you think about having the primary communicated method be to manually set it up with a special note that you can try the alpha web ui if you're not using docker. This might reprioritize the communication to emphasize supported features. I'd also ideally love to see this move to an organization with some consolidation of repos. Docs being separate actually makes it pretty hard to reason about.

**Comment by zpnk** [comment]
deploy.now now has docker support! (zpnk/deploy.now#8) The deploy button on https://stage.now.sh/ should finally work, haha.

@jimthedev Thanks for the note about changing the docs - if we continue to run into issues with the deploy button, I'm definitely for figuring out a better way of communicating the installation method.

Also, re: GH org/repo consolidation: all for consolidating `zpnk/stage.now` & `zpnk/stage-ci`. Any advice for going about this? I think `zpnk/stage-ci` should stay the "canonical" repo because it has all the issues/PRs, but the `stage.now` name makes more sense. For an org - any name suggestions? Would ideally house `zpnk/deploy.now` and the stage project.

Closing this issue, but let's open a new issue to further discuss the GH org/repo unification!

**Comment by paulirish** [comment]
> Closing this issue, but let's open a new issue to further discuss the GH org/repo unification!

When you do this, I have a few things to add. 🤓
